
import Modele.GameEvent;
import Modele.GameListener;
import Modele.Player;
import Modele.SimpleTwoPlayersGameModel;
import View.SimpleBoardGameView;
import View.SimpleGameControlView;
import View.SimplePlayerView;
import com.sun.media.jfxmedia.events.PlayerEvent;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author arnaud
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    SimpleTwoPlayersGameModel model;
    SimpleBoardGameView boardView;
    SimplePlayerView p1View;
    SimplePlayerView p2View;
    SimpleGameControlView cView;
    
    public Main() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Player p1 = new Player("CHONG ENG", new Color(200,50,150));
        Player p2 = new Player("TRONQ UI", new Color(50,200,150));
        model = new SimpleTwoPlayersGameModel(p1, p2);
        boardView = new SimpleBoardGameView(model);
        p1View = new SimplePlayerView(model, p1);
        p2View = new SimplePlayerView(model, p2);
        cView = new SimpleGameControlView(model);
        
        JPanel playersPanel = new JPanel(new BorderLayout());
        playersPanel.setBounds(0, 0, 150, 600);
        playersPanel.add(p1View, BorderLayout.WEST);
        playersPanel.add(p2View, BorderLayout.EAST);
        add(playersPanel, BorderLayout.NORTH);
        
        add(boardView, BorderLayout.CENTER);
        add(cView, BorderLayout.SOUTH);
        
        model.addViewListener(boardView);
        model.addViewListener(p1View);
        model.addViewListener(p2View);
        
        setSize(890, 350);
        
        boardView.setVisible(false);
        p1View.setVisible(false);
        p2View.setVisible(false);
        model.addGameListener(new GameListener() {

            @Override
            public void GamePlayerChanged(GameEvent e) {
                
            }

            @Override
            public void GameIsOver(GameEvent e) {
                Player p = (Player) e.getSource();
               String msg = "The game is over";
                if(p!=null) {
                    msg = "The winner is " + p.getName();
                }
                JOptionPane.showMessageDialog(null,msg,"GAME OVER",JOptionPane.OK_OPTION);
                repaint();
            }

            @Override
            public void GamehasBeggun(GameEvent e) {
                boardView.setVisible(true);
        p1View.setVisible(true);
        p2View.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
