/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetretestbeans;

import java.awt.Color;
import java.awt.FlowLayout;
import java.util.ArrayList;
import shapelabel.ShapeLabel;
import shapelabel.ShapeLabelEvent;
import shapelabel.ShapeLabelListener;

/**
 *
 * @author ladoucar
 */
public class AvailableTokens extends javax.swing.JPanel {
    private ArrayList<ShapeLabel> availabletoken = new ArrayList<>();
    private ShapeLabelListener listener = new ShapeLabelListener() {

        @Override
        public void ShapeLabelMouseClicked(ShapeLabelEvent e) {
            shapelabel.ShapeLabel sl = (shapelabel.ShapeLabel)e.getSource();
            setShapeLabelInvisible(sl);
            sl.setEnabled(false);
            sl.removeShapeLabelClicked(listener);
//remove((shapelabel.ShapeLabel)e.getSource());
            //availabletoken.remove((shapelabel.ShapeLabel)e.getSource());
            revalidate();
            getParent().repaint();
        }

        private void setShapeLabelInvisible(ShapeLabel sl) {
            sl.setBackground(Color.WHITE);
            sl.setForeground(Color.GRAY);
        }
    };

    /**
     * Creates new form AvailableTokens
     */
    public AvailableTokens() {
        initComponents();
        setLayout(new FlowLayout());
        for (int i=0; i<10; ++i){
            shapelabel.ShapeLabel sl = new ShapeLabel(""+(i+1), Color.black, Color.YELLOW);
            add(sl);
            availabletoken.add(sl);
            sl.addShapeLabelClicked(listener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
